
<?php
$mellCmd = '&#109;&#097;&#105;&#108;&#116;&#111;:&#099;&#104;&#117;&#114;&#099;&#104;&#064;&#104;&#105;&#103;&#104;&#108;&#097;&#110;&#100;&#112;&#099;&#046;&#099;&#111;&#109;';
$mellMe = '&#099;&#104;&#117;&#114;&#099;&#104;&#064;&#104;&#105;&#103;&#104;&#108;&#097;&#110;&#100;&#112;&#099;&#046;&#099;&#111;&#109;';
?>

<html>

<head>
<meta name="GENERATOR" content="Microsoft FrontPage 6.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="keywords" content="highland park church, evangelical christian,
evangelical, christian, kokomo, indiana, creed, bible-believing, awana, camp
emmanuel, biblical preaching, tabernacle ministries, vasicek, messianic judaism,
edification, prayers">
<meta name="description" content="<?php print $strDescr; ?>">
<meta name="verify-v1" content="1Pa72EAP4TYyDTEftxroVozo/1WbidBc4QzxAFdtuFI=" />
<link rel="stylesheet" type="text/css" href="https://www.highlandpc.com/style20.css">
<link rel="icon" href="https://www.highlandpc.com/favicon.ico" type="image/x-icon">
<link rel="shortcut icon" href="https://www.highlandpc.com/favicon.ico" type="image/x-icon">
<title><?php print $strTitle; ?></title>
<script language=javascript type="text/javascript">
   <!--

   function scripture(msg) {
       bibleWindow = window.open(msg, "bibleWin", "width=500,height=250,scrollbars=yes")
       bibleWindow.focus()
   }

	// -->
</script>
</head>

<body>

<!--
<div class="wrapper">
-->
<a href="https://www.highlandpc.com/"><img border="0" src="https://www.highlandpc.com/images/logos/hpccrln.gif" width="227" height="60" alt="Highland Park Church"></a>


<div class="drpdwn" style="float:right;">
  <button class="drpbtn"><a href="https://www.highlandpc.com/aboutus/index.php#contact" class="drpbtn">contact</a></button>
</div>

<div class="drpdwn" style="float:right;">
  <button class="drpbtn">deepen &#9662;</button>
  <div class="drpdwn-content">
    <a href="https://www.highlandpc.com/articles/">articles</a>
    <a href="https://www.highlandpc.com/prayers/">prayers</a>
    <a href="https://www.highlandpc.com/sermaudi/">sermons</a>
  </div>
</div>

<div class="drpdwn" style="float:right;">
  <button class="drpbtn">connect &#9662;</button>
  <div class="drpdwn-content">
    <a href="https://www.highlandpc.com/aboutus/adult.php">adults</a>
    <a href="https://www.highlandpc.com/kids/">children</a>
    <a href="https://www.highlandpc.com/youth/">youth</a>
  </div>
</div>

<div class="drpdwn" style="float:right;">
  <button class="drpbtn">reach &#9662;</button>
  <div class="drpdwn-content">
    <a href="https://www.highlandpc.com/aboutus/awana.php">awana</a>
    <a href="https://www.highlandpc.com/aboutus/cefgnc.php">good news club</a>
    <a href="https://www.highlandpc.com/aboutus/missapr.php">missions</a>
  </div>
</div>

<div class="drpdwn" style="float:right;">
  <button class="drpbtn">beliefs &#9662;</button>
  <div class="drpdwn-content">
    <a href="https://www.highlandpc.com/aboutus/const.php">constitution</a>
    <a href="https://www.highlandpc.com/aboutus/creed.php">creed</a>
    <a href="https://www.highlandpc.com/how2bsvd.php">how to be saved</a>
    <a href="https://www.highlandpc.com/aboutus/minappr.php">ministry approach</a>
    <a href="https://www.highlandpc.com/articles/chrchmsn.php">mission statement article</a>
    <a href="https://www.highlandpc.com/aboutus/purpples.php">purpose & principles</a>
    <a href="https://www.highlandpc.com/webeliev.php">we believe</a>
  </div>
</div>

<div class="drpdwn" style="float:right;">
  <button class="drpbtn">about &#9662;</button>
  <div class="drpdwn-content">
    <a href="https://www.highlandpc.com/aboutus/whoweare.php">at a glance</a>
    <a href="https://www.highlandpc.com/aboutus/history.php">history</a>
    <a href="https://www.highlandpc.com/aboutus/member.php">membership</a>
    <a href="https://www.highlandpc.com/aboutus/pastored.php">our pastor</a>
    <a href="https://www.highlandpc.com/meetschd.php">service schedule</a>
  </div>
</div>

<div class="drpdwn" style="float:right;">
  <button class="drpbtn"><a href="https://www.highlandpc.com/" class="drpbtn">welcome</a></button>
</div>  

<!--
 <div class="outer">
  <div class="inner">

   <div class="colleft">
    <div align="left" id="rollovr">
	 <table border="1" cellpadding="0" cellspacing="0" style="border-collapse: collapse" id="table1" class="rollmenu" align="center">
		<tr>
&nbsp;
		</tr>
	</table>
   </div>
  </div>
  <div class="colmid">
-->  