<script type="text/javascript">
<!--
	document.write('<img src="https://www.highlandpc.com/cgi-bin/axs/ax.pl?mode=img&ref=');
	document.write( escape( document.referrer ) );
	document.write('" height="1" width="1" style="display:none" alt="" />');
// -->
</script><noscript>
	<img src="https://www.highlandpc.com/cgi-bin/axs/ax.pl?mode=img" height="1" width="1" style="display:none" alt="" />
</noscript>


  <div class="ftr">
   <table align="right"><tr><td><br><form method="get" action="https://www.highlandpc.com/cgi-bin/search/search.pl">
   <input name="Terms" id="fdse_TermsEx" />
   <input type="submit" value="Search" />
   </form></td></tr></table><p><span class="sm">Highland Park Church&nbsp;&nbsp; 
   <nobr>516 W. Sycamore St.</nobr> <nobr>Kokomo, Indiana, 46901 USA&nbsp;&nbsp; </nobr> 
   (765)452-1779</span> 
   &nbsp;&nbsp;&nbsp;<a href="<?php print $mellCmd; ?>"><?php print $mellMe; ?></a>
   &nbsp;&nbsp;&nbsp;<span class="sm"><nobr>Main Service: Sun 10:30 a.m.</nobr></span>
   <br></p> 
  </div>

</body>
</html>