<br>
<div class="ftr">
<p align="center">Reprinted from the <?php print $strDate; ?> Body Builder, a publication of Highland Park Church.</p>
</div>

<div class="ftr">
  <p><span class="sm">Highland Park Church&nbsp;&nbsp; 
  <nobr>516 W. Sycamore St.</nobr> <nobr>Kokomo, Indiana, 46901 USA&nbsp;&nbsp; </nobr> 
  (765)452-1779</span> 
  &nbsp;&nbsp;&nbsp;<a href="<?php print $mellCmd; ?>"><?php print $mellMe; ?></a>
  &nbsp;&nbsp;&nbsp;<span class="sm"><nobr>Main Service: Sun 10:30 a.m.</nobr></span>
  <br></p> 
</div>

</body>
</html>