    <table border="0" cellpadding="0" cellspacing="0" width="100%">
     <tr>
      <td width="68%"></td>
      <td width="32%"><a href="<?php print $mellCmd; ?>"><img border="0" src="https://www.highlandpc.com/images/edsig.gif" width="109" height="35" alt="Pastor Ed"></a></td>
     </tr>
    </table>
    <br>

<div class="ftr">
  <p><span class="sm">Highland Park Church&nbsp;&nbsp; 
  <nobr>516 W. Sycamore St.</nobr> <nobr>Kokomo, Indiana, 46901 USA&nbsp;&nbsp; </nobr> 
  (765)452-1779</span> 
  &nbsp;&nbsp;&nbsp;<a href="<?php print $mellCmd; ?>"><?php print $mellMe; ?></a>
  &nbsp;&nbsp;&nbsp;<span class="sm"><nobr>Main Service: Sun 10:30 a.m.</nobr></span>
  <br></p> 
</div>

</body>
</html>
